"""Macro to write dart_proto_library output to the source tree for IDE analysis."""

load("@aspect_bazel_lib//lib:write_source_files.bzl", "write_source_files")
load("@bazel_skylib//rules:write_file.bzl", "write_file")

def _target_name(label_str):
    """Extract the target name from a label string.

    Args:
        label_str: A Bazel label string like "//pkg:target" or ":target" or "target".

    Returns:
        The target name component.
    """
    if ":" in label_str:
        return label_str.rsplit(":", 1)[1]
    if "/" in label_str:
        return label_str.rsplit("/", 1)[1]
    return label_str

def dart_proto_analysis_package(name, dart_proto, path, package_name = None, grpc = False, **kwargs):
    """Writes generated proto Dart files to the source tree for IDE analysis.

    Creates a directory at `path` containing a `pubspec.yaml` and a `lib/`
    directory with the generated `.pb.dart` files. This makes the generated
    code visible to the Dart analysis server for autocomplete, go-to-definition,
    and error checking.

    Run `bazel run :<name>` to sync the files. A `<name>_test` target is
    automatically created to check staleness in CI.

    Each dart_proto_library target should get its own analysis package:

    ```starlark
    dart_proto_analysis_package(
        name = "write_echo_analysis_pkg",
        dart_proto = "//echo:echo_dart_proto",
        path = "echo_analysis",
    )
    ```

    Args:
        name: Target name. Running `bazel run :<name>` syncs the files.
        dart_proto: Label of the dart_proto_library target.
        path: Source-tree directory to write the analysis package into.
        package_name: Dart package name for the generated pubspec.yaml.
            Defaults to the dart_proto target name.
        grpc: If True, include `grpc` as a dependency in the generated
            pubspec.yaml (needed when dart_proto uses grpc = True).
        **kwargs: Additional arguments forwarded to write_source_files
            (e.g. visibility, tags).
    """
    pkg_name = package_name or _target_name(dart_proto)

    pubspec_name = name + "_pubspec"
    lines = [
        "# GENERATED BY dart_proto_analysis_package -- DO NOT EDIT",
        "name: %s" % pkg_name,
        "environment:",
        "  sdk: ^3.4.0",
        "dependencies:",
        "  protobuf: ^6.0.0",
    ]
    if grpc:
        lines.append("  grpc: ^5.1.0")
    lines.append("")  # trailing newline

    write_file(
        name = pubspec_name,
        out = pubspec_name + ".yaml",
        content = lines,
    )

    write_source_files(
        name = name,
        files = {
            path + "/lib": dart_proto,
            path + "/pubspec.yaml": ":" + pubspec_name,
        },
        suggested_update_target = "//%s:%s" % (native.package_name(), name),
        **kwargs
    )
